#!/bin/sh

if [ ! -f /etc/postfix/sasl_passwd.db ]; then
    echo $SES_HOST":"$SES_PORT $SES_USER":"$SES_SECRET && postmap hash:/etc/postfix/sasl_passwd && \
        rm /etc/postfix/sasl_passwd && chown root:root /etc/postfix/sasl_passwd.db && \
        chmod 0600 /etc/postfix/sasl_passwd.db
fi
